import React from 'react';
import { ArrowRightIcon } from './Icons';

const HeroSection: React.FC<{ onGeneratorClick: () => void }> = ({ onGeneratorClick }) => {
  return (
    <section className="py-20 sm:py-32 bg-gray-50 dark:bg-dark-bg">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <h1 className="text-4xl sm:text-5xl md:text-7xl font-extrabold tracking-tight text-gray-900 dark:text-light-text">
          Your Personal <span className="text-primary-light dark:text-primary">AI Fitness</span> Coach
        </h1>
        <p className="mt-6 max-w-2xl mx-auto text-lg text-gray-600 dark:text-gray-text">
          Stop guessing, start training. Get personalized workout and nutrition plans generated by our advanced AI to achieve your fitness goals faster than ever.
        </p>
        <div className="mt-10 flex justify-center">
          <button
            onClick={onGeneratorClick}
            className="group inline-flex items-center justify-center px-6 py-3 border border-transparent text-base font-medium rounded-md text-white dark:text-secondary bg-primary-light dark:bg-primary hover:bg-opacity-90 transition-transform hover:scale-105"
          >
            Try the Generator
            <ArrowRightIcon className="ml-2 w-5 h-5 transform group-hover:translate-x-1 transition-transform" />
          </button>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;